# -*- coding: utf-8 -*-
"""Copy of Linaer_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YemjlK2qFLwNTtFKKtGQd2Pv5vkjATyZ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv('FishData.csv')
print(df.head())

print(df.shape)

print(df.isnull().sum())

print(df.describe())

df['Species'].value_counts()

df1 = df.drop(['Length1','Length2','Length3'], axis=1)

df2= df1.drop('Species', axis=1)

print(df2.head())

X ,Y = df2.drop('Weight', axis=1), df2['Weight'].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=42, train_size=0.7)

reg=LinearRegression()
reg.fit(X_train, Y_train)

print(reg.coef_)

r2_score = reg.score(X_test, Y_test)
print(r2_score)

reg.predict([[11, 4]])

Y_prediction=reg.predict(X_test)

from sklearn.metrics import r2_score
r2_score(Y_test,Y_prediction)

